import { defineConfig, devices } from '@playwright/test'
import fs from 'node:fs'
import dotenv from 'dotenv'

// Local convenience: load Supabase creds generated by `npm run supabase:env`.
// This lets `npm run e2e` work without manual exporting.
dotenv.config({ path: '.env.local' })
if (fs.existsSync('.env.supabase')) {
  dotenv.config({ path: '.env.supabase', override: true })
}

const isCI = !!process.env.CI

export default defineConfig({
  testDir: './e2e/tests',
  globalSetup: './e2e/global-setup.ts',
  globalTeardown: './e2e/global-teardown.ts',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  reporter: process.env.CI ? 'github' : 'html',
  use: {
    baseURL: `http://localhost:${process.env.E2E_PORT ?? '3000'}`,
    trace: 'on-first-retry',
  },
  // Local dev: set reuseExistingServer=true so a running `npm run dev` is used.
  // CI: builds the app first, then this starts the Nitro server.
  webServer: {
    command: isCI ? 'node .output/server/index.mjs' : `npx vite dev --port ${process.env.E2E_PORT ?? '3000'}`,
    url: `http://localhost:${process.env.E2E_PORT ?? '3000'}`,
    reuseExistingServer: !isCI,
    timeout: 30_000,
    env: {
      PORT: process.env.E2E_PORT ?? '3000',
      VITE_SUPABASE_URL: process.env.VITE_SUPABASE_URL ?? process.env.SUPABASE_URL ?? 'http://127.0.0.1:54321',
      VITE_SUPABASE_ANON_KEY: process.env.VITE_SUPABASE_ANON_KEY ?? process.env.SUPABASE_ANON_KEY ?? '',
      SUPABASE_URL: process.env.SUPABASE_URL ?? 'http://127.0.0.1:54321',
      // Server-side client uses SUPABASE_KEY. Allow either env name.
      SUPABASE_KEY: process.env.SUPABASE_KEY ?? process.env.SUPABASE_SERVICE_ROLE_KEY ?? '',
      // E2E global setup uses SUPABASE_SERVICE_ROLE_KEY. Keep it available.
      SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_KEY ?? '',
    },
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
})
