#!/usr/bin/env bash
set -euo pipefail

# Generates `.env.supabase` from a running local Supabase instance.
# - Starts Supabase if needed.
# - Waits briefly for API + keys to be available.

if ! docker info >/dev/null 2>&1; then
  echo "ERROR: Docker is not running. Start Docker Desktop, then re-run."
  exit 1
fi

STATUS=$(supabase status -o env 2>/dev/null || true)
if ! echo "$STATUS" | grep -q '^API_URL='; then
  echo "Supabase not fully running — starting..."
  supabase start
  STATUS=$(supabase status -o env 2>/dev/null || true)
fi

for i in $(seq 1 15); do
  if echo "$STATUS" | grep -q '^API_URL=' \
    && echo "$STATUS" | grep -q '^ANON_KEY=' \
    && echo "$STATUS" | grep -q '^SERVICE_ROLE_KEY='; then
    break
  fi
  echo "Waiting for Supabase services... ($i)"
  sleep 2
  STATUS=$(supabase status -o env 2>/dev/null || true)
done

API_URL=$(echo "$STATUS" | grep '^API_URL=' | cut -d'"' -f2)
ANON_KEY=$(echo "$STATUS" | grep '^ANON_KEY=' | cut -d'"' -f2)
SERVICE_ROLE_KEY=$(echo "$STATUS" | grep '^SERVICE_ROLE_KEY=' | cut -d'"' -f2)

if [ -z "${API_URL:-}" ] || [ -z "${ANON_KEY:-}" ] || [ -z "${SERVICE_ROLE_KEY:-}" ]; then
  echo "ERROR: Supabase services not ready. Try: supabase stop && supabase start"
  exit 1
fi

cat > .env.supabase <<EOF
# Generated by scripts/supabase-env-file.sh
SUPABASE_URL=$API_URL
SUPABASE_KEY=$SERVICE_ROLE_KEY
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY

VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
EOF

echo "Wrote local Supabase credentials to .env.supabase"
