/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FunRouteImport } from './routes/fun'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as StravaConnectRouteImport } from './routes/strava.connect'
import { Route as StravaCallbackRouteImport } from './routes/strava.callback'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FunRoute = FunRouteImport.update({
  id: '/fun',
  path: '/fun',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaConnectRoute = StravaConnectRouteImport.update({
  id: '/strava/connect',
  path: '/strava/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const StravaCallbackRoute = StravaCallbackRouteImport.update({
  id: '/strava/callback',
  path: '/strava/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fun': typeof FunRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/workouts': typeof WorkoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/strava/connect': typeof StravaConnectRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fun': typeof FunRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/workouts': typeof WorkoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/strava/connect': typeof StravaConnectRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fun': typeof FunRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/workouts': typeof WorkoutsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/strava/callback': typeof StravaCallbackRoute
  '/strava/connect': typeof StravaConnectRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fun'
    | '/login'
    | '/logout'
    | '/rss.xml'
    | '/workouts'
    | '/blog/$slug'
    | '/strava/callback'
    | '/strava/connect'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fun'
    | '/login'
    | '/logout'
    | '/rss.xml'
    | '/workouts'
    | '/blog/$slug'
    | '/strava/callback'
    | '/strava/connect'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/fun'
    | '/login'
    | '/logout'
    | '/rss.xml'
    | '/workouts'
    | '/blog/$slug'
    | '/strava/callback'
    | '/strava/connect'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FunRoute: typeof FunRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  WorkoutsRoute: typeof WorkoutsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  StravaCallbackRoute: typeof StravaCallbackRoute
  StravaConnectRoute: typeof StravaConnectRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fun': {
      id: '/fun'
      path: '/fun'
      fullPath: '/fun'
      preLoaderRoute: typeof FunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava/connect': {
      id: '/strava/connect'
      path: '/strava/connect'
      fullPath: '/strava/connect'
      preLoaderRoute: typeof StravaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strava/callback': {
      id: '/strava/callback'
      path: '/strava/callback'
      fullPath: '/strava/callback'
      preLoaderRoute: typeof StravaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FunRoute: FunRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  WorkoutsRoute: WorkoutsRoute,
  BlogSlugRoute: BlogSlugRoute,
  StravaCallbackRoute: StravaCallbackRoute,
  StravaConnectRoute: StravaConnectRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
