drop extension if exists "pg_net";


  create table "public"."site_views" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_ip" text,
    "url" text
      );


alter table "public"."site_views" enable row level security;

CREATE UNIQUE INDEX site_views_pkey ON public.site_views USING btree (id);

alter table "public"."site_views" add constraint "site_views_pkey" PRIMARY KEY using index "site_views_pkey";

create or replace view "public"."page_view_counts" as  SELECT site_views.url,
    count(*) AS count
   FROM public.site_views
  GROUP BY site_views.url;


grant delete on table "public"."site_views" to "anon";

grant insert on table "public"."site_views" to "anon";

grant references on table "public"."site_views" to "anon";

grant select on table "public"."site_views" to "anon";

grant trigger on table "public"."site_views" to "anon";

grant truncate on table "public"."site_views" to "anon";

grant update on table "public"."site_views" to "anon";

grant delete on table "public"."site_views" to "authenticated";

grant insert on table "public"."site_views" to "authenticated";

grant references on table "public"."site_views" to "authenticated";

grant select on table "public"."site_views" to "authenticated";

grant trigger on table "public"."site_views" to "authenticated";

grant truncate on table "public"."site_views" to "authenticated";

grant update on table "public"."site_views" to "authenticated";

grant delete on table "public"."site_views" to "service_role";

grant insert on table "public"."site_views" to "service_role";

grant references on table "public"."site_views" to "service_role";

grant select on table "public"."site_views" to "service_role";

grant trigger on table "public"."site_views" to "service_role";

grant truncate on table "public"."site_views" to "service_role";

grant update on table "public"."site_views" to "service_role";


  create policy "Enable access to all users"
  on "public"."site_views"
  as permissive
  for select
  to public
using (true);



  create policy "Enable insert access to all users"
  on "public"."site_views"
  as permissive
  for insert
  to public
with check (true);



